#!/usr/bin/env python3
"""
emit_pack.py — write a design-system pack from probe evidence plus your decisions.

The probe records what a brand artefact contains; YOU decide what those observations mean
(which colour is `primary`, which sizes are real ramp steps). This script does the mechanical
half: it assembles those decisions into the pack layout a deck engine expects, fills the
skeleton in ../assets/skeleton/, and keeps the evidence alongside as PROVENANCE.md so anyone
can audit where a token came from.

It deliberately does NOT invent values. A decisions file missing a role produces a pack with
that role absent — visible and fixable — rather than a plausible default that nobody notices.

Usage:
    emit_pack.py --evidence evidence.json --decisions decisions.json --out <pack dir>

See ../references/pack-contract.md for the decisions.json schema and what every field feeds.
"""
import argparse
import json
import os
import shutil
import sys

RULES_DEFAULT = {
    "requireSlideCanvas": True, "requireInlineTailwindConfig": True, "requireFooterText": True,
    "requireFontMarker": True, "requireCanonicalScaler": True, "requireDataTemplate": True,
    "enforceFontSizeFloor": True, "enforceTokenValues": True, "enforceGradientCanon": True,
    "enforcePaletteCensus": True, "banTailwindDefaultPalette": True, "banOffScaleFontWeights": True,
    "banOffBrandFontFamilies": True, "banEmoji": True, "banStructuralShadows": True,
    "banLeftAccentBars": True, "banElementCollisions": True, "checkFontUrlsResolve": False,
}


def die(msg):
    sys.exit(f"error: {msg}")


def js_tailwind(prefix, colors, scale, gradients, stack, font_class, radii, tracking):
    def q(v):
        return json.dumps(v)

    lines = ["tailwind.config = {", "  theme: {", "    extend: {", "      colors: {"]
    for name, hexv in colors.items():
        lines.append(f"        '{prefix}-{name}': '{hexv}',")
    lines += ["      },", "", "      fontFamily: {",
              f"        {font_class.replace('font-', '')}: [{', '.join(q(s) for s in stack)}],",
              "      },", "", "      fontSize: {"]
    for name, st in scale.items():
        extra = []
        if st.get("lineHeight"):
            extra.append(f"lineHeight: '{st['lineHeight']}'")
        if st.get("fontWeight"):
            extra.append(f"fontWeight: '{st['fontWeight']}'")
        meta = "{ " + ", ".join(extra) + " }" if extra else "{}"
        lines.append(f"        '{prefix}-{name}': ['{st['size']}', {meta}],")
    lines += ["      },"]
    if gradients:
        lines += ["", "      backgroundImage: {"]
        for name, val in gradients.items():
            lines.append(f"        '{prefix}-{name}': '{val}',")
        lines += ["      },"]
    if tracking:
        lines += ["", "      letterSpacing: {"]
        for name, val in tracking.items():
            lines.append(f"        '{prefix}-{name}': '{val}',")
        lines += ["      },"]
    if radii:
        lines += ["", "      borderRadius: {"]
        for name, val in radii.items():
            lines.append(f"        '{prefix}-{name}': '{val}',")
        lines += ["      },"]
    lines += ["    },", "  },", "};"]
    return "\n".join(lines)


def fill(text, mapping):
    for k, v in mapping.items():
        text = text.replace("{{" + k + "}}", str(v))
    return text




def write_pack_skill(out, dec, prefix, colors, roles, gradients, typo, built, manifest):
    """Write the pack's own SKILL.md.

    The engine's SKILL.md files tell the designer to consult the PACK for brand specifics —
    which tokens exist, what the gradient is, which templates are available. A pack without
    that document sends the designer looking for a file that is not there, so the forge
    generates it rather than leaving it to whoever remembers.

    It carries the brand half only. The craft half — layout, typography practice, SVG and
    chart rules — lives once in the engine's references/design-craft.md, because it does not
    change when the brand does.
    """
    p = dec["prefix_label"] if "prefix_label" in dec else prefix
    lines = [f"---", f"name: design-system", f"description: |",
             f"  {dec['name']} — the brand knowledge base for this pack. Token names and values,",
             f"  gradients, the type scale, and the template library. Read this whenever you need a",
             f"  concrete brand value; read the engine's references/design-craft.md for how to use it.",
             f"---", "",
             f"# {dec['name']} (knowledge base)", "",
             f"Generated by design-system-forge from this pack's manifest. Everything below is",
             f"derived from `design-system.json` and `tailwind.config.js`, so it cannot drift from",
             f"the tokens the validator enforces — regenerate the pack and this file follows.", "",
             "## Stack", "",
             f"- Canvas **{manifest['canvas']['width']}×{manifest['canvas']['height']}**, scaled to fit by the scaler in `slide-base.html`",
             f"- Tailwind Play CDN with an inline config (a snapshot of `tailwind.config.js`)",
             f"- Token prefix `{p}-` · font utility `{typo.get('fontUtilityClass','')}`",
             f"- Typeface: {typo.get('familyLabel') or 'system stack'}",
             "", "## Tokens", "",
             "| token | hex | role |", "|---|---|---|"]
    role_of = {}
    for r, t in roles.items():
        if isinstance(t, str):
            role_of.setdefault(t, []).append(r)
    for name, hexv in colors.items():
        lines.append(f"| `{p}-{name}` | `{hexv}` | {', '.join(role_of.get(name, [])) or '—'} |")

    viz = roles.get("viz")
    if isinstance(viz, list) and viz:
        lines += ["", f"Chart series order: {' → '.join(f'`{p}-{v}`' for v in viz)}. "
                      "Adjacent series must stay distinguishable; do not reorder casually."]

    lines += ["", "## Type scale", "", "| step | size | line-height | weight |", "|---|---|---|---|"]
    for name, s in (dec.get("typeScale") or {}).items():
        lines.append(f"| `text-{p}-{name}` | {s.get('size','')} | {s.get('lineHeight','—')} | {s.get('fontWeight','—')} |")
    lines += ["", f"Nothing below **{typo.get('minFontSizePx',14)}px**. Weights are limited to "
                  f"{', '.join(str(w) for w in typo.get('allowedWeights', []))} — anything else fails the audit."]

    if gradients:
        lines += ["", "## Gradients", ""]
        for name, val in gradients.items():
            lines.append(f"- `bg-{p}-{name}` — `{val}`")
        lines += ["", "These are the only sanctioned gradients; the validator rejects near-misses, so "
                      "copy them exactly rather than retyping the stops.",
                  "", "Small text does not go on a gradient. One foreground colour cannot clear 4.5:1 "
                      "against both the light and the dark end, so gradient slides use large text and "
                      "inverted chrome."]

    lines += ["", "## Template library", "",
              "Copy a template verbatim to start a slide — the `data-template` attribute is how the "
              "validator knows a slide came from the pack rather than from memory.", "",
              "| file | what it is for |", "|---|---|"]
    for t in built:
        lines.append(f"| `templates/{t['file']}` | {t['description']} |")
    lines += ["", "These are a floor, not a ceiling: they are generated from this pack's tokens so "
                  "they are correct and on-brand, not so they are the best possible slide. A brief "
                  "that deserves a bespoke layout should get one.",
              "", "## Where the craft rules live", "",
              "Layout, typography practice, SVG and chart rules are brand-independent and live once "
              "in the engine, at `references/design-craft.md`. This file is only the brand half.", ""]
    with open(os.path.join(out, "SKILL.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


def main():
    ap = argparse.ArgumentParser(description="Assemble a design-system pack from evidence + decisions.")
    ap.add_argument("--evidence", default=None,
                    help="Probe output. Omit only with --authored.")
    ap.add_argument("--authored", action="store_true",
                    help="This pack was DESIGNED, not extracted from a brand artefact (a neutral "
                         "starter pack, or one typed from a written brand spec). Provenance then "
                         "records that honestly instead of implying evidence that does not exist.")
    ap.add_argument("--decisions", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--force", action="store_true", help="Overwrite an existing pack directory")
    args = ap.parse_args()

    here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    skel = os.path.join(here, "assets", "skeleton")

    if args.evidence:
        with open(args.evidence, encoding="utf-8") as f:
            ev = json.load(f)
    elif args.authored:
        ev = {"source": {"path": "(authored — no source artefact)", "kind": "authored",
                         "observations": 0}, "theme": {}, "colors": [], "type": [],
              "dropped_as_noise": 0, "notes": ["Pack was authored, not extracted. Every value "
                                               "here is a design decision, so the usual question "
                                               "\'is this really the brand\'s?\' is answered by "
                                               "whoever wrote it, not by a source file."]}
    else:
        die("pass --evidence <probe output>, or --authored for a pack you are designing yourself")
    with open(args.decisions, encoding="utf-8") as f:
        dec = json.load(f)

    for req in ("id", "name", "tokens", "roles", "typography", "typeScale"):
        if req not in dec:
            die(f"decisions.json is missing '{req}' — see references/pack-contract.md")
    prefix = dec["tokens"].get("prefix") or dec["id"]
    colors = dec["tokens"].get("colors") or {}
    if not colors:
        die("decisions.json declares no colours; a pack without tokens cannot validate anything")

    roles = dec["roles"]
    for role in ("primary", "ink", "body", "muted", "rule", "surface"):
        if role not in roles:
            print(f"  warn: role '{role}' unfilled — engines asking for it will get nothing",
                  file=sys.stderr)
    unknown = [r for r, t in roles.items() if isinstance(t, str) and t not in colors]
    if unknown:
        die(f"roles point at tokens that do not exist: {unknown}")

    out = os.path.abspath(os.path.expanduser(args.out))
    if os.path.exists(out) and not args.force:
        die(f"{out} already exists — pass --force to overwrite, or extend the existing pack")
    os.makedirs(os.path.join(out, "templates"), exist_ok=True)

    typo = dec["typography"]
    stack = typo.get("stack") or [typo.get("familyLabel", "sans-serif"), "sans-serif"]
    font_class = typo.get("fontUtilityClass", f"font-{prefix}")
    gradients = dec.get("gradients") or {}
    cfg = js_tailwind(prefix, colors, dec["typeScale"], gradients, stack, font_class,
                      dec.get("radii") or {}, dec.get("tracking") or {})

    def cls(role, kind="text"):
        tok = roles.get(role)
        return f"{kind}-{prefix}-{tok}" if tok else ""

    brand_gradient = gradients.get("brand") or gradients.get(next(iter(gradients), ""), "") or \
        f"linear-gradient(60deg, {colors[roles['primary']]} 0%, {colors[roles['primary']]} 100%)"
    canvas = dec.get("canvas") or {"width": 1920, "height": 1080}
    footer = dec.get("footer") or {}
    mapping = {
        "PACK_NAME": dec["name"], "P": prefix, "TAILWIND_CONFIG": cfg,
        "CANVAS_W": canvas["width"], "CANVAS_H": canvas["height"],
        "FONT_STACK": ", ".join(f"'{s}'" if " " in s else s for s in stack),
        "FONT_CLASS": font_class, "BRAND_GRADIENT": brand_gradient,
        "MUTED_CLASS": cls("muted"), "INK_CLASS": cls("ink"), "BODY_CLASS": cls("body"),
        "FOOTER_LABEL": footer.get("label", ""),
        # The footer chrome is engine-owned, not slide content, but its text still has to
        # clear the pack's own floor — a pack with a floor above 16px (large-type systems
        # like a cinema-scale deck) would otherwise fail its own rule on every slide.
        "FOOTER_SIZE_PX": max(int(typo.get("minFontSizePx", 16)), 16),
    }

    base = fill(open(os.path.join(skel, "slide-base.html"), encoding="utf-8").read(), mapping)
    with open(os.path.join(out, "slide-base.html"), "w", encoding="utf-8") as f:
        f.write(base)

    # Baseline templates are DERIVED from the pack's own tokens rather than copied from a
    # skeleton, so a pack forged from a brand that supplied only colours still arrives able
    # to make a deck. See scripts/archetypes.py for why layout is arithmetic here.
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    import archetypes
    marker = "  <!-- ── BODY CONTENT GOES HERE ───────────────────────── -->"
    built = archetypes.build(prefix, roles, dec["typeScale"], canvas, gradients,
                             footer.get("label", ""), typo.get("minFontSizePx", 14))
    for t in built:
        page = base.replace(marker, t["body"])
        page = page.replace('data-template="base"', f'data-template="{t["template"]}"')
        if t["gradient"]:
            # Inline, not a utility class: slide-base paints #slide white through an ID
            # selector, which outranks any class, so a class-based gradient silently loses
            # and leaves pale text on white. Inline style outranks the ID rule.
            # The solid background-color is both a real fallback and what the contrast
            # checker can actually read — a gradient it cannot parse would otherwise be
            # scored against white and reported as illegible.
            solid = colors.get(roles.get("deep") or roles.get("primary"), "")
            paint = f"background-color:{solid};" if solid else ""
            paint += f'background-image:{gradients[t["gradient"]]};'
            page = page.replace('<div id="slide" data-template',
                                f'<div id="slide" style="{paint}" data-template')
            # Chrome has to invert with the background. slide-base sets the footer in the
            # muted role, which is chosen to sit on the light surface — measured at 1.08:1
            # over this gradient, i.e. invisible. A dark slide takes the on-dark colour
            # throughout, chrome included.
            muted_tok, on_dark_tok = roles.get("muted"), roles.get("surface")
            anchor = '<div id="slide"'
            if muted_tok and on_dark_tok and anchor in page:
                head, body_part = page.split(anchor, 1)
                # Only class USES get swapped. The inline tailwind.config in <head> defines
                # what the tokens mean; rewriting a colour there redefines the token and the
                # pack stops matching its own manifest.
                body_part = body_part.replace(f"-{prefix}-{muted_tok}", f"-{prefix}-{on_dark_tok}")
                page = head + anchor + body_part
        with open(os.path.join(out, "templates", t["file"]), "w", encoding="utf-8") as f:
            f.write(page)

    # The fixture must use hexes the pack does NOT own, or the census check has nothing to catch.
    owned = {v.upper() for v in colors.values()}
    off = [h for h in ("#D97757", "#F5F1E8", "#FF00AA", "#123456") if h not in owned]
    fixture = fill(open(os.path.join(skel, "off-brand-fixture.html"), encoding="utf-8").read(),
                   {"OFF_PALETTE_HEX": off[0], "OFF_PALETTE_HEX_2": off[1]})
    with open(os.path.join(out, "off-brand-fixture.html"), "w", encoding="utf-8") as f:
        f.write(fixture)

    with open(os.path.join(out, "tailwind.config.js"), "w", encoding="utf-8") as f:
        f.write(cfg + "\n")

    rules = dict(RULES_DEFAULT)
    rules.update(dec.get("rules") or {})
    manifest = {
        "$comment": [
            f"Generated by design-system-forge from {os.path.basename(ev['source']['path'])}.",
            "Every token here traces to an observation recorded in PROVENANCE.md. Values marked",
            "there as inferred (rather than declared by the source's theme) deserve a human look",
            "before this pack is trusted for client-facing work.",
        ],
        # The interface version between pack and engine. An engine refuses a MAJOR it does
        # not implement, so a pack that stops matching its engine says so at load instead of
        # half-working. Bump minor when the contract gains an optional field; bump major when
        # a required one changes shape or disappears.
        "contractVersion": dec.get("contractVersion", "1.0"),
        "id": dec["id"], "name": dec["name"], "version": dec.get("version", "1.0"),
        "canvas": canvas,
        # Only declare a directory the pack actually has. The engine discovers what a pack
        # provides through these keys, so declaring an empty or absent folder would send the
        # designer looking for files that are not there — the exact failure this indirection
        # exists to prevent. An absent key is a clear answer: "this pack ships none".
        "tokens": dict({"prefix": prefix, "configFile": "tailwind.config.js",
                        "baseFile": "slide-base.html", "templatesDir": "templates"},
                       **{k: v for k, v in (("snippetsDir", "snippets"), ("chartsDir", "charts"))
                          if os.path.isdir(os.path.join(out, v))}),
        "typography": {
            "minFontSizePx": typo.get("minFontSizePx", 14),
            "allowedWeights": typo.get("allowedWeights", [300, 400, 700]),
            "fontUtilityClass": font_class,
            "familyRequiredPattern": typo.get("familyRequiredPattern", typo.get("familyMarker", "")),
            "familyMarker": typo.get("familyMarker", ""),
            "familyLabel": typo.get("familyLabel", ""),
        },
        "footer": footer,
        "gradients": {
            "brandHexMarkers": dec.get("gradientMarkers", []),
            "canonical": [v.replace(" ", "") for v in gradients.values()],
        },
        "palette": {"censusExcludesInlineConfig": True,
                    "censusSources": ["tailwind.config.js", "slide-base.html", "templates/*.html"]},
        "roles": roles,
        "rules": rules,
        "collisionTolerancePx": dec.get("collisionTolerancePx", 4),
        "licensing": dec.get("licensing", {
            "assetsRedistributable": False,
            "note": "Client brand values and any font files in this pack are not covered by the "
                    "pipeline's licence. Confirm redistribution rights before sharing.",
        }),
    }
    for extra in ("svg", "pptx", "charts", "iconPolicy", "editor", "exemptions", "ruleNotes"):
        if extra in dec:
            manifest[extra] = dec[extra]
    with open(os.path.join(out, "design-system.json"), "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2, ensure_ascii=False)
        f.write("\n")

    authored = ev["source"]["kind"] == "authored"
    write_pack_skill(out, dec, prefix, colors, roles, gradients, typo, built, manifest)

    lines = [f"# Provenance — {dec['name']}", ""]
    if authored:
        lines += ["**Authored, not extracted.** No brand artefact was probed; every token below "
                  "is a design decision made by whoever wrote this pack. Treat it as a starting "
                  "point to be replaced by a real brand, not as a record of one.", ""]
    else:
        lines += [f"Source: `{ev['source']['path']}` ({ev['source']['kind']}, "
                  f"{ev['source']['observations']} colour observations)", ""]
    if ev.get("theme", {}).get("colors"):
        lines += ["The source declared a theme, so colours marked **declared** below are the "
                  "brand's own values, not inferences.", ""]
    if authored:
        lines += ["| token | hex |", "|---|---|"]
        for name, hexv in colors.items():
            lines.append(f"| `{prefix}-{name}` | {hexv} |")
    else:
        lines += ["| token | hex | source | area weight | pages |", "|---|---|---|---|---|"]
    by_hex = {c["hex"].upper(): c for c in ev.get("colors", [])}
    for name, hexv in ({} if authored else colors).items():
        c = by_hex.get(hexv.upper())
        if c:
            src = "declared" if c.get("snapped_to_theme") else "inferred"
            # Read the weight defensively: an evidence file written by an older probe uses
            # the previous field name, and provenance is not worth crashing a whole pack
            # over. Missing weight prints as unknown rather than taking the run down.
            w = c.get("area_weight", c.get("area_share"))
            w_txt = f"{w:.4f}" if isinstance(w, (int, float)) else "—"
            lines.append(f"| `{prefix}-{name}` | {hexv} | {src} | "
                         f"{w_txt} | {c.get('pages', '—')} |")
        else:
            lines.append(f"| `{prefix}-{name}` | {hexv} | **no evidence — justify or drop** | — | — |")
    lines += ["", f"Dropped as noise during probing: {ev.get('dropped_as_noise', 0)} colour cluster(s).", ""]
    if ev.get("notes"):
        lines += ["## Probe notes", ""] + [f"- {n}" for n in ev["notes"]] + [""]
    with open(os.path.join(out, "PROVENANCE.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    if args.evidence:
        shutil.copyfile(args.evidence, os.path.join(out, "evidence.json"))

    unevidenced = [] if authored else [n for n, h in colors.items() if h.upper() not in by_hex]
    print(f"wrote pack -> {out}")
    print(f"  SKILL.md, {len(built)} template(s), {len(colors)} token(s), {len(dec['typeScale'])} type step(s), "
          f"{len(gradients)} gradient(s), {sum(1 for v in rules.values() if v)} rule(s) on")
    if unevidenced:
        print(f"  warn: {len(unevidenced)} token(s) with no probe evidence: "
              f"{', '.join(unevidenced)}", file=sys.stderr)
    print("  next: verify_pack.py --pack " + out)


if __name__ == "__main__":
    main()
