#!/usr/bin/env python3
"""
apply_edits.py — materialise staged review edits into the slide files.

The review harness's Edit mode records direct manipulations as selector -> declaration
patches (kind:"edit" annotations, projected to <deck>/edits.json). Nothing in the harness
touches a slide file. This script is the one place those patches reach disk, and it does
it the least invasive way there is: a single inline

    <style id="deck-review-edits"> … </style>

block appended to each affected slide's <head>. No DOM rewriting, no reformatting, no
external stylesheet (relative paths do not resolve in the harness's srcdoc iframes or
under file://) — just a block that is inserted, replaced, or removed wholesale, so every
run is idempotent and the diff is readable.

Because extract_ir.py reads getComputedStyle at the native canvas size and pdf-export
screenshots the rendered slide, an override here flows correctly into BOTH exports.

THE OVERRIDE LAYER IS A STAGING AREA, NOT A DESTINATION. Only annotations still `open`
are written. Promote an edit into the slide's real markup — tokens and classes, re-audited
— mark it `resolved` (annotations.py resolve <id>), then re-run this script: the rule
disappears from the block on its own, and the block disappears when the last one is gone.

Usage:
    apply_edits.py --deck-dir <deck>            # write/refresh the block in every slide
    apply_edits.py --deck-dir <deck> --check    # report only, touch nothing (exit 1 if stale)
    apply_edits.py --deck-dir <deck> --strip    # remove the block from every slide
"""
import argparse
import json
import re
import sys
from pathlib import Path

BLOCK_ID = "deck-review-edits"
BLOCK_RE = re.compile(
    r"[ \t]*<style id=\"" + BLOCK_ID + r"\">.*?</style>\n?",
    re.DOTALL | re.IGNORECASE,
)
HEADER = (
    "/* Staged review edits — generated by deck-review/scripts/apply_edits.py.\n"
    "   DO NOT EDIT BY HAND and do not ship a deck that still carries this block.\n"
    "   Each rule is an OPEN kind:\"edit\" annotation from the review harness. Promote it\n"
    "   into the markup above (tokens/classes, re-audited), mark the annotation resolved,\n"
    "   then re-run apply_edits.py and the rule drops out by itself. */"
)


def load_edits(deck: Path) -> list:
    """Open edits, preferring annotations.json — it is the contract the gate reads.

    edits.json is a projection the harness writes for convenience; if the two ever
    disagree, the annotations file wins, because that is what carries the statuses.
    """
    ann = deck / "annotations.json"
    if ann.exists():
        try:
            data = json.loads(ann.read_text(encoding="utf-8"))
            items = data.get("annotations", []) if isinstance(data, dict) else (data or [])
            return [a for a in items if a.get("kind") == "edit"]
        except json.JSONDecodeError as e:
            sys.exit(f"error: {ann} is not valid JSON: {e}")
    ej = deck / "edits.json"
    if ej.exists():
        try:
            return json.loads(ej.read_text(encoding="utf-8")).get("edits", [])
        except json.JSONDecodeError as e:
            sys.exit(f"error: {ej} is not valid JSON: {e}")
    return []


def css_for(edits: list) -> str:
    out = []
    for e in edits:
        decl = e.get("decl") or {}
        sel = (e.get("selector") or "").strip()
        if not decl or not sel:
            continue
        # The harness counted how many elements this selector hits, back when a DOM
        # existed to ask. Anything but exactly one would restyle bystanders, so it is
        # reported and skipped rather than written.
        n = e.get("selector_matches", 1)
        if n != 1:
            print(f"  skipped {e.get('id','?')}: selector matches {n} elements, not 1 "
                  f"({sel}) — re-do it as a comment", file=sys.stderr)
            continue
        body = "\n".join(f"  {k}: {v} !important;" for k, v in decl.items())
        note = " ".join((e.get("comment") or "").split())
        out.append(f"/* {e.get('id', '?')} — {note} */\n{sel} {{\n{body}\n}}")
    return "\n\n".join(out)


def block_for(css: str) -> str:
    return f'<style id="{BLOCK_ID}">\n{HEADER}\n{css}\n</style>\n'


def write_slide(path: Path, css: str) -> str:
    """Insert / replace / remove the block. Returns what happened."""
    src = path.read_text(encoding="utf-8")
    had = bool(BLOCK_RE.search(src))
    stripped = BLOCK_RE.sub("", src)
    if not css:
        if not had:
            return "unchanged"
        path.write_text(stripped, encoding="utf-8")
        return "removed"
    if "</head>" not in stripped.lower():
        return "SKIPPED (no </head>)"
    # Insert immediately before </head> so the block is the last thing in the head:
    # with !important it wins regardless, but last-in-head also beats the Tailwind
    # Play CDN's runtime-injected styles on equal specificity.
    idx = stripped.lower().index("</head>")
    out = stripped[:idx] + block_for(css) + stripped[idx:]
    path.write_text(out, encoding="utf-8")
    return "replaced" if had else "inserted"


def main() -> None:
    ap = argparse.ArgumentParser(description="Materialise staged review edits into slide files.")
    ap.add_argument("--deck-dir", required=True)
    ap.add_argument("--strip", action="store_true", help="Remove the override block from every slide")
    ap.add_argument("--check", action="store_true", help="Report only; exit 1 if any slide is out of date")
    args = ap.parse_args()

    deck = Path(args.deck_dir).expanduser().resolve()
    if not deck.is_dir():
        sys.exit(f"error: deck dir not found: {deck}")

    slides = sorted(p for p in deck.iterdir()
                    if p.is_file() and re.match(r"^\d{2}-.*\.html$", p.name, re.IGNORECASE))
    if not slides:
        sys.exit(f"error: no NN-*.html slides in {deck}")

    edits = load_edits(deck)
    openish = [e for e in edits if e.get("status", "open") == "open"]
    promoted = len(edits) - len(openish)

    by_file: dict[str, list] = {}
    for e in openish:
        by_file.setdefault(e.get("slide_file", ""), []).append(e)

    if args.check:
        stale = 0
        for p in slides:
            has_block = bool(BLOCK_RE.search(p.read_text(encoding="utf-8")))
            want = bool(css_for(by_file.get(p.name, [])))
            if has_block != want:
                print(f"  stale: {p.name} (block present={has_block}, expected={want})")
                stale += 1
        print(f"-- {len(openish)} open edit(s), {promoted} promoted, {stale} slide(s) out of date")
        sys.exit(1 if stale else 0)

    counts: dict[str, int] = {}
    for p in slides:
        css = "" if args.strip else css_for(by_file.get(p.name, []))
        what = write_slide(p, css)
        counts[what] = counts.get(what, 0) + 1
        if what not in ("unchanged",):
            print(f"  {what:22} {p.name}")

    if args.strip:
        print(f"-- stripped the override block from {counts.get('removed', 0)} slide(s)")
    else:
        print(f"-- {len(openish)} open edit(s) across {len(by_file)} slide(s); "
              f"{promoted} already promoted (not written)")
        if promoted and not openish:
            print("   every edit is promoted — the override layer is empty and the deck is export-clean")
        elif openish:
            print("   NOT export-clean: promote these into the slide source, resolve them, then re-run.")


if __name__ == "__main__":
    main()
